<?php
namespace PatternSeek\ComponentView\Test;

use PatternSeek\ComponentView\AbstractViewComponent;
use PatternSeek\ComponentView\TwigTemplate;

/**
 * Class HelloViewComponent
 * @package PatternSeek\ComponentView\Test
 */
class HelloViewComponent extends AbstractViewComponent{

    /**
     * Has the component been initialised?
     * @return bool
     */
    public function getInitialised()
    {
        return ( isset( $this->state[ 'initialised' ] ) && ( $this->state[ 'initialised' ] === true ) );
    }

    /**
     * Using $props and $this->state, optionally update state, optionally create child components via addOrUpdateChild(), return template props
     * @param array $props
     * @return array Template props
     */
    protected function doUpdate( array $props ){
        $this->testInputs(
            [
                'anyTypeRequired'=>[],
                'anyTypeRequired2'=>[null],
                'anyTypeOptional'=>[null,null],
                'boolRequired'=>['bool'],
                'boolRequired2'=>['boolean'],
                'intOptional'=>['int',3],
                'intRequired'=>['integer'],
                'doubleRequired'=>['double'],
                'floatRequired'=>['float'],
                'stringRequired'=>['string'],
                'name'=>['string'],
                'arrayRequired'=>['array'],
                'objectRequired'=>['object'],
                'resourceRequired'=>['resource'],
                'callableRequired'=>['callable'],
                'SomeClassRequired'=>['PatternSeek\ComponentView\Test\SomeClass'],
                'SomeClassOptional'=>['PatternSeek\ComponentView\Test\SomeClass',null],
                'SomeClassWithPrebuiltDefault'=>['PatternSeek\ComponentView\Test\SomeClass', new SomeClass()],
            ],
            $props
        );

        $this->addOrUpdateChild(
            "world",
            "\\PatternSeek\\ComponentView\\Test\\WorldViewComponent",
            [   // This is just passing specific parent inputs to the child
                'name'=>$props['name'],
                'intRequired'=>$props['intRequired']
            ]
        );

        // Normally there would be processing here and $this->state might be populated or modified, but not in this case

        $templateInputs = $props; // normally this would be generated by some processing
        return $templateInputs;

    }

    /**
     * Load or configure the component's template as necessary
     *
     * @return void
     */
    protected function setupTemplate()
    {
        $tplTwig = <<<EOS
Hello {{component( 'world' )}}
EOS;

        $this->template = new TwigTemplate( $this, $tplTwig );
    }
}