<?php
namespace PatternSeek\ComponentView\Test;

use PatternSeek\ComponentView\AbstractViewComponent;
use PatternSeek\ComponentView\TwigTemplate;

/**
 * Class HelloViewComponent
 * @package PatternSeek\ComponentView\Test
 */
class HelloViewComponent extends AbstractViewComponent{

    protected function doUpdate( array $inputs ){
        $this->testInputs(
            [
                'anyTypeRequired'=>[],
                'anyTypeRequired2'=>[null],
                'anyTypeOptional'=>[null,null],
                'boolRequired'=>['bool'],
                'boolRequired2'=>['boolean'],
                'intOptional'=>['int',3],
                'intRequired'=>['integer'],
                'doubleRequired'=>['double'],
                'floatRequired'=>['float'],
                'stringRequired'=>['string'],
                'name'=>['string'],
                'arrayRequired'=>['array'],
                'objectRequired'=>['object'],
                'resourceRequired'=>['resource'],
                'callableRequired'=>['callable'],
                'SomeClassRequired'=>['PatternSeek\ComponentView\Test\SomeClass'],
                'SomeClassOptional'=>['PatternSeek\ComponentView\Test\SomeClass',null],
                'SomeClassWithPrebuiltDefault'=>['PatternSeek\ComponentView\Test\SomeClass', new SomeClass()],
            ],
            $inputs
        );

        $this->addOrUpdateChild(
            "world",
            "\\PatternSeek\\ComponentView\\Test\\WorldViewComponent",
            [   // This is just passing specific parent inputs to the child
                'name'=>$inputs['name'],
                'intRequired'=>$inputs['intRequired']
            ]
        );

        // Normally there would be processing here and $this->state might be populated or modified, but not in this case

        $templateInputs = $inputs; // normally this would be generated by some processing
        return $templateInputs;

    }

    /**
     * Load or configure the component's template as necessary
     *
     * @return void
     */
    protected function setupTemplate()
    {
        $tplTwig = <<<EOS
{% set worldOut = components.world.render() %}Hello {{worldOut.content}}
EOS;

        $this->template = new TwigTemplate( $this, $tplTwig );
    }
}