<?php
namespace PatternSeek\ComponentView\Test;

use PatternSeek\ComponentView\AbstractViewComponent;
use PatternSeek\ComponentView\TwigTemplate;
use PatternSeek\ComponentView\ViewComponentResponse;

/**
 * Class WorldViewComponent
 * @package PatternSeek\ComponentView\Test
 */
class WorldViewComponent extends AbstractViewComponent{

    protected function doUpdate( array $props ){

        $this->testInputs(
            [
                'name'=>['string'],
                'intRequired'=>['integer']
            ],
            $props
        );

        // Used by jsonMultiplyHandler()
        $this->state['intRequired'] = $props['intRequired'];

        $templateInputs = $props; // normally this would be generated by some processing
        return $templateInputs;
    }

    protected function jsonMultiplyHandler( $args ){
        $this->testInputs( ['multiplier'=>['int']], $args );
        $resInt = $this->state['intRequired'] * $args['multiplier'];
        return new ViewComponentResponse( "application/json", json_encode( ['result'=>$resInt] ) );
    }

    protected function setStateHandler( $args ){
        $this->testInputs( ['something'=>['int']], $args );
        $this->state['testProp'] = $args['something'];
        return new ViewComponentResponse( "text/plain", "OK" );
    }

    protected function getStateHandler( $args ){
        return new ViewComponentResponse( "text/plain", $this->state['testProp'] );
    }

    /**
     * Load or configure the component's template as necessary
     *
     * @return void
     */
    protected function setupTemplate()
    {
        $tplTwig = <<<EOS
World. From: {{props.name}}
EOS;
        $this->template = new TwigTemplate( $this, $tplTwig );
    }
}